from typing import Protocol, Optional, List

class UserRepository(Protocol):
    """
    Este é o CONTRATO. Ele define O QUE o serviço pode fazer com dados de usuário,
    mas não se importa em COMO isso é feito (se é com Mongo, SQL, ou um arquivo de texto).
    """
    def find_by_id(self, user_id: str) -> Optional[dict]: ...
    def find_all(self) -> List[dict]: ...
    def save(self, user_data: dict) -> dict: ...
    def delete(self, user_id: str) -> None: ...